## 주요 라이브러리 
- pandas : 데이터 처리 및 분석
- numpy : 과학계산 및 수학계산
     - C, C++ 로 작성됨
- scipy : 과학계산 및 통계
- tensorflow : 머신러닝, 딥러닝
- keras : 신경망, 딥러닝
- matplotlib, seaborn, plotly : 시각화

1. 넘파이 배열
    - 벡터(1차원), 매트릭스(2차원)
    - 머신러닝에서 사용하는 데이터 구조
    - ndarray 구조

In [3]:
import numpy as np

In [4]:
# 1 차원 배열

arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
arr1.shape

(3,)

In [ ]:
# 2 차원 (메트릭스 )

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr3 = np.array([[1,2,3]])
print(arr3)
print(arr3.shape)

[[1 2 3]]
(1, 3)


In [8]:
print("차원",arr1.ndim)
print("차원",arr2.ndim)
print("차원",arr3.ndim)

차원 1
차원 2
차원 2


In [9]:
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [10]:
print(arr1.dtype)
print(type(arr1))

int64
<class 'numpy.ndarray'>


In [11]:
arr1.astype('float64')

array([1., 2., 3.])

## 넘파이 배열 생성 함수

In [ ]:
# arange(숫자) : 0 ~ 숫자(미포함) 가 들어간 array 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,3), dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.zeros((3,2,3), dtype='int64')

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.zeros((2,5), dtype='int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.empty(4)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.08058228e-312])

In [23]:
np.empty((3,4), dtype='int64')

array([[      1837955140280,                  50,                   0,
                          0],
       [  32370056113422336, 4048292297953142123, 3256718499316851761,
        4122539877624735287],
       [3615657368688799024, 3474635080246453817, 8386112019188965687,
        4123383228866327413]])

In [24]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [26]:
# 단위행렬 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.eye(6, k=-1)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [29]:
# 균등하게 분할된 값 반환
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
# random : 0 <= x < 1
np.random.rand(2,3)

array([[0.67525503, 0.42066713, 0.4873525 ],
       [0.05212404, 0.14125987, 0.31479861]])

In [32]:
# 정규분포로 샘플링 된 랜덤 값

np.random.randn()

0.11332158492537699

In [33]:
np.random.randn(5)

array([-0.48125398, -1.49984835, -0.01124601,  0.93901751, -2.24257522])

In [35]:
# 1 ~ 10 숫자 중에서 무작위로 5개 추출

np.random.randint(1,10,5)

array([5, 6, 9, 5, 6], dtype=int32)

In [38]:
np.random.seed(25)
np.random.randint(1,100,(3,5))

array([[ 5, 63, 91, 16, 62],
       [24, 45, 51,  9, 29],
       [ 5, 90, 32, 70,  2]], dtype=int32)

In [ ]:

np.random.choice(100,(3,4))

array([[39,  3, 88, 55],
       [ 3, 84, 45,  3],
       [ 1, 22, 31, 48]], dtype=int32)

In [43]:
arr1 = np.array([1,23,1.5,2.6,4.9])

np.random.choice(arr1,(2,2))

array([[4.9, 1.5],
       [1. , 2.6]])

In [44]:
# replace=False : 중복없이 추출

np.random.choice(arr1,(2,2),replace=False)

array([[23. ,  2.6],
       [ 4.9,  1.5]])

In [50]:
# 인덱싱, 슬라이싱

arr1 = np.arange(1, 10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
print(arr1[3])
print(arr1[3:])
print(arr1[3:8])

4
[4 5 6 7 8 9]
[4 5 6 7 8]


In [52]:
# 1 차원 => 2 차원

arr2 = arr1.reshape(3, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
print(arr2[0])
print(arr2[0:2, 0:1])

[1 2 3]
[[1]
 [4]]


In [55]:
arr1[arr1 % 2 == 0]

array([2, 4, 6, 8])

In [56]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[2,2,2]])

In [57]:
x + y

array([[2, 3, 4],
       [6, 7, 8]])

In [58]:
np.add(x, y)

array([[2, 3, 4],
       [6, 7, 8]])

In [59]:
x - y

array([[0, 1, 2],
       [2, 3, 4]])

In [60]:
np.subtract(x,y)

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 1  2  3]
 [ 8 10 12]]
[[ 1  2  3]
 [ 8 10 12]]


In [62]:
print(x/y)
print(np.divide(x,y))

[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]
